controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    
    wheel_separation: 0.25  # Adjust to your robot's actual measurements
    wheel_radius: 0.05      # Adjust to your robot's actual measurements
    
    publish_rate: 50.0
    
    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.5    # m/s
        has_acceleration_limits: true
        max_acceleration: 1.0 # m/s^2
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0    # rad/s
        has_acceleration_limits: true
        max_acceleration: 2.0 # rad/s^2